{% set version = "0.18.0" %}

package:
  name: openapi-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openapi-core/openapi_core-{{ version }}.tar.gz
  sha256: ede9fe3a2b0a7f8870249c085b2d7e64b7bb169b46ceeaa3b812cceff2b05548

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
  run:
    - asgiref >=3.6.0,<4.0.0
    - backports.cached-property >=1.0.2,<2.0.0
    - isodate
    - jsonschema >=4.17.3,<5.0.0
    - jsonschema-spec >=0.1.6,<0.2.0
    - lazy-object-proxy >=1.7.1,<2.0.0
    - more-itertools
    - openapi-schema-validator >=0.4.2,<0.5.0
    - openapi-spec-validator >=0.5.0,<0.6.0
    - parse
    - python >=3.7
    - typing_extensions >=4.5.0,<5.0.0
    - werkzeug

test:
  source_files:
    - tests
  imports:
    - openapi_core
  commands:
    - pip check
    - pytest -vv --cov=openapi_core --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=91
  requires:
    - aiohttp
    - django
    - djangorestframework
    - httpx
    - falcon
    - flask
    - pip
    - pytest-aiohttp
    - pytest-cov
    - requests
    - responses
    - starlette
    - webob

about:
  home: https://github.com/p1c2u/openapi-core
  summary: client-side and server-side support for the OpenAPI Specification v3
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
