{% set version = "0.19.4" %}

# added on https://github.com/conda-forge/openapi-core-feedstock/pull/22
{% set skips = [
  "test_request_response_error",
  "test_spec_invalid",
  "test_spec_not_detected",
  "test_webhook_request_validator_not_found",
  "test_spec_not_detected",
  "test_spec_not_supported",
  "test_webhook_response_validator_not_found",
] %}

package:
  name: openapi-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openapi-core/openapi_core-{{ version }}.tar.gz
  sha256: 1150d9daa5e7b4cacfd7d7e097333dc89382d7d72703934128dcf8a1a4d0df49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - poetry-core >=1.0.0
  run:
    - isodate
    - jsonschema >=4.18.0,<5.0.0
    - jsonschema-path >=0.3.1,<0.4.0
    - more-itertools
    - openapi-schema-validator >=0.6.0,<0.7.0
    - openapi-spec-validator >=0.7.1,<0.8.0
    - parse
    - python >=3.8
    - werkzeug

test:
  source_files:
    - tests
  imports:
    - openapi_core
  commands:
    - pip check
    - coverage run --source=openapi_core --branch -m pytest -vv  -k "not ({{ skips | join(" or ") }})"
    - coverage report --show-missing --skip-covered --fail-under=91
  requires:
    - aiohttp
    - aioitertools
    - coverage
    - django
    - djangorestframework
    - falcon
    - fastapi
    - flask
    - httpx
    - pip
    - pytest
    - pytest-aiohttp
    - requests
    - responses
    - starlette
    - webob

about:
  home: https://github.com/p1c2u/openapi-core
  summary: client-side and server-side support for the OpenAPI Specification v3
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
