{% set version = "0.19.0" %}

package:
  name: openapi-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openapi-core/openapi_core-{{ version }}.tar.gz
  sha256: 9c0a157ca8e21a1205f95e0495557a45ad2a33bc8f0f9002406d671420b0920a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - poetry-core >=1.0.0
  run:
    - asgiref >=3.6.0,<4.0.0
    - isodate
    - jsonschema >=4.18.0,<5.0.0
    - jsonschema-spec >=0.2.3,<0.3.0
    - more-itertools
    - openapi-schema-validator >=0.6.0,<0.7.0
    - openapi-spec-validator >=0.7.1,<0.8.0
    - parse
    - python >=3.8
    - werkzeug

test:
  source_files:
    - tests
  imports:
    - openapi_core
  commands:
    - pip check
    - pytest -vv --cov=openapi_core --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=91
  requires:
    - aiohttp
    - django
    - djangorestframework
    - httpx
    - falcon
    - flask
    - pip
    - pytest-aiohttp
    - pytest-cov
    - requests
    - responses
    - starlette
    - webob

about:
  home: https://github.com/p1c2u/openapi-core
  summary: client-side and server-side support for the OpenAPI Specification v3
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
