{% set version = "0.16.2" %}

package:
  name: openapi-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/openapi-core/openapi_core-{{ version }}.tar.gz
  sha256: 3c0ff39a70f8599c4303dc87247763f731481c39fc014c7ba72e30f1016c662d

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    # from poetry-generated setup.py
    - isodate
    - jsonschema-spec >=0.1.1,<0.2.0
    - more-itertools
    - openapi-schema-validator >=0.3.0,<0.4.0
    - openapi-spec-validator >=0.5.0,<0.6.0
    - parse
    - pathable >=0.4.0,<0.5.0
    - typing-extensions >=4.3.0,<5.0.0
    - werkzeug

test:
  imports:
    - openapi_core
    - openapi_core.casting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p1c2u/openapi-core
  summary: client-side and server-side support for the OpenAPI Specification v3
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
