# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.22.0"
  python_check_max: "3.14"

package:
  name: openapi-core
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/openapi-core/openapi_core-${{ version }}.tar.gz
  sha256: b30490dfa74e3aac2276105525590135212352f5dd7e5acf8f62f6a89ed6f2d0

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry-core >=1.0.0
  run:
    - isodate
    - jsonschema >=4.23.0,<5.0.0
    - jsonschema-path >=0.3.4,<0.4.0
    - more-itertools
    - openapi-schema-validator >=0.6.0,<0.7.0
    - openapi-spec-validator >=0.7.1,<0.8.0
    - python >=${{ python_min }}
    - typing_extensions >=4.8.0,<5.0.0
    - werkzeug >=2.1.0

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
      imports: openapi_core
  - files:
      source:
        - tests/
    requirements:
      run:
        - aiohttp
        - aioitertools
        - coverage
        - django
        - djangorestframework
        - falcon
        - fastapi
        - flask
        - httpx
        - pytest
        - pytest-aiohttp
        - python ${{ python_min }}.*
        - requests
        - responses
        - starlette
        - webob
    script:
      file: run_test.py

about:
  summary: client-side and server-side support for the OpenAPI Specification v3
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/openapi-core
  repository: https://github.com/python-openapi/openapi-core
  documentation: https://openapi-core.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
