# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.20.0"

package:
  name: openapi-core
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/openapi-core/openapi_core-${{ version }}.tar.gz
  sha256: 3de7fcc635139875da0e2102b7de96f1b42738365a2f99d7eef6e835839cc649

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - poetry-core >=1.0.0
  run:
    - isodate
    - jsonschema >=4.18.0,<5.0.0
    - jsonschema-path >=0.3.1,<0.4.0
    - more-itertools
    - openapi-schema-validator >=0.6.0,<0.7.0
    - openapi-spec-validator >=0.7.1,<0.8.0
    - parse
    - python >=${{ python_min }}
    - typing_extensions >=4.8.0,<5.0.0
    - werkzeug <3.1.2

tests:
  - python:
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
      imports: openapi_core
  - files:
      recipe:
        - run_test.py
      source:
        - tests/
    requirements:
      run:
        - aiohttp
        - aioitertools
        - coverage
        - django
        - djangorestframework
        - falcon
        - fastapi
        - flask
        - httpx
        - pytest
        - pytest-aiohttp
        - python ${{ python_min }}.*
        - requests
        - responses
        - starlette
        - webob
    script:
      - python run_test.py

about:
  summary: client-side and server-side support for the OpenAPI Specification v3
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/p1c2u/openapi-core

extra:
  recipe-maintainers:
    - bollwyvl
